version: '3.3'

volumes:
  mongodb-data-container:
    driver: local

services:
  db:
    image: mongo:latest
    container_name: mongodb
    restart: always
#    expose:
#      - 27017
    ports:
      - "27017:27017"
    environment:
      TZ: America/Sao_Paulo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: builders
#    volumes:
#      - mongodb-data-container:/data/db

  maven:
    container_name: maven
    build: './docker/maven'
    volumes:
      - ./:/home/app
    working_dir: /home/app

  app:
    image: builders-customer-service
    container_name: builders-customer-service-app
    build:
      context: .
      dockerfile: 'docker/app/Dockerfile'
    network_mode: 'host'
    volumes:
      - .:/home/app
    working_dir: /home/app
    ports:
      - "8080:8080"
    depends_on:
      - "db"