version: '3.3'

services:
  test-db:
    image: mongo:latest
    container_name: mongodb
    restart: always
    expose:
      - 27018
    ports:
      - "27018:27018"
    environment:
      TZ: America/Sao_Paulo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: builders-test
    networks:
      netBackEnd:
        ipv4_address: 192.168.0.2

  db:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      TZ: America/Sao_Paulo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: builders

  maven:
    container_name: maven
    build: './docker/maven'
    volumes:
      - ./:/home/app
    working_dir: /home/app

  app:
    image: builders-customer-service
    container_name: builders-customer-service-app
    build:
      context: .
      dockerfile: 'docker/app/Dockerfile'
    network_mode: 'host'
    volumes:
      - .:/home/app
    working_dir: /home/app
    ports:
      - "8080:8080"
    depends_on:
      - "db"

networks:
  netBackEnd:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24